eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: automatic-task
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/MySQL?characterEncoding=UTF-8&useSSL-false&&serverTimezone=Asia/Shanghai
    username: root
    password: QWER1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:timeoutInMilliseconds: 10000

myJobCron:
  gatherStoreJob: '0 0/30 * * * ? '
  emailRemindJob: '0 0/30 * * * ? '
  getFundDWJZJob: '0 0/30 * * * ? '

customUrl:
  fundMainUrl: 'http://127.0.0.1:8031/api-data/getFundMain/'
  allFundMainUrl: 'http://127.0.0.1:8031/api-data/fundMains'
  synchroUrl: 'https://api.doctorxiong.club/v1/fund/detail?code='
  thirdUrl: 'https://fundf10.eastmoney.com/F10DataApi.aspx?type=lsjz&code='