eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: localhost
    instance-id: localhost:${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
